// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/project.proto

package projectpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_proto_project_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_proto_project_proto_rawDescGZIP(), []int{0}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_proto_project_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_project_proto_rawDescGZIP(), []int{1}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

type GetProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProjectRequest) Reset() {
	*x = GetProjectRequest{}
	mi := &file_proto_project_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectRequest) ProtoMessage() {}

func (x *GetProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectRequest.ProtoReflect.Descriptor instead.
func (*GetProjectRequest) Descriptor() ([]byte, []int) {
	return file_proto_project_proto_rawDescGZIP(), []int{2}
}

func (x *GetProjectRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListProjectsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProjectsRequest) Reset() {
	*x = ListProjectsRequest{}
	mi := &file_proto_project_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProjectsRequest) ProtoMessage() {}

func (x *ListProjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProjectsRequest.ProtoReflect.Descriptor instead.
func (*ListProjectsRequest) Descriptor() ([]byte, []int) {
	return file_proto_project_proto_rawDescGZIP(), []int{3}
}

type CreateProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ImageName     string                 `protobuf:"bytes,2,opt,name=image_name,json=imageName,proto3" json:"image_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProjectRequest) Reset() {
	*x = CreateProjectRequest{}
	mi := &file_proto_project_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProjectRequest) ProtoMessage() {}

func (x *CreateProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProjectRequest.ProtoReflect.Descriptor instead.
func (*CreateProjectRequest) Descriptor() ([]byte, []int) {
	return file_proto_project_proto_rawDescGZIP(), []int{4}
}

func (x *CreateProjectRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProjectRequest) GetImageName() string {
	if x != nil {
		return x.ImageName
	}
	return ""
}

type ProjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ImageName     string                 `protobuf:"bytes,3,opt,name=image_name,json=imageName,proto3" json:"image_name,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectResponse) Reset() {
	*x = ProjectResponse{}
	mi := &file_proto_project_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectResponse) ProtoMessage() {}

func (x *ProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectResponse.ProtoReflect.Descriptor instead.
func (*ProjectResponse) Descriptor() ([]byte, []int) {
	return file_proto_project_proto_rawDescGZIP(), []int{5}
}

func (x *ProjectResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProjectResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProjectResponse) GetImageName() string {
	if x != nil {
		return x.ImageName
	}
	return ""
}

func (x *ProjectResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListProjectsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Projects      []*ProjectResponse     `protobuf:"bytes,1,rep,name=projects,proto3" json:"projects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProjectsResponse) Reset() {
	*x = ListProjectsResponse{}
	mi := &file_proto_project_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProjectsResponse) ProtoMessage() {}

func (x *ListProjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProjectsResponse.ProtoReflect.Descriptor instead.
func (*ListProjectsResponse) Descriptor() ([]byte, []int) {
	return file_proto_project_proto_rawDescGZIP(), []int{6}
}

func (x *ListProjectsResponse) GetProjects() []*ProjectResponse {
	if x != nil {
		return x.Projects
	}
	return nil
}

type ProjectURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectURLResponse) Reset() {
	*x = ProjectURLResponse{}
	mi := &file_proto_project_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectURLResponse) ProtoMessage() {}

func (x *ProjectURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectURLResponse.ProtoReflect.Descriptor instead.
func (*ProjectURLResponse) Descriptor() ([]byte, []int) {
	return file_proto_project_proto_rawDescGZIP(), []int{7}
}

func (x *ProjectURLResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

var File_proto_project_proto protoreflect.FileDescriptor

const file_proto_project_proto_rawDesc = "" +
	"\n" +
	"\x13proto/project.proto\x12\aproject\"\x0f\n" +
	"\rHealthRequest\"B\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\"#\n" +
	"\x11GetProjectRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\x15\n" +
	"\x13ListProjectsRequest\"I\n" +
	"\x14CreateProjectRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"image_name\x18\x02 \x01(\tR\timageName\"l\n" +
	"\x0fProjectResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"image_name\x18\x03 \x01(\tR\timageName\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"L\n" +
	"\x14ListProjectsResponse\x124\n" +
	"\bprojects\x18\x01 \x03(\v2\x18.project.ProjectResponseR\bprojects\"&\n" +
	"\x12ProjectURLResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url2\xf0\x02\n" +
	"\x0eProjectService\x129\n" +
	"\x06Health\x12\x16.project.HealthRequest\x1a\x17.project.HealthResponse\x12B\n" +
	"\n" +
	"GetProject\x12\x1a.project.GetProjectRequest\x1a\x18.project.ProjectResponse\x12K\n" +
	"\fListProjects\x12\x1c.project.ListProjectsRequest\x1a\x1d.project.ListProjectsResponse\x12H\n" +
	"\rCreateProject\x12\x1d.project.CreateProjectRequest\x1a\x18.project.ProjectResponse\x12H\n" +
	"\rGetProjectURL\x12\x1a.project.GetProjectRequest\x1a\x1b.project.ProjectURLResponseB\x1dZ\x1bforge/gen/project;projectpbb\x06proto3"

var (
	file_proto_project_proto_rawDescOnce sync.Once
	file_proto_project_proto_rawDescData []byte
)

func file_proto_project_proto_rawDescGZIP() []byte {
	file_proto_project_proto_rawDescOnce.Do(func() {
		file_proto_project_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_project_proto_rawDesc), len(file_proto_project_proto_rawDesc)))
	})
	return file_proto_project_proto_rawDescData
}

var file_proto_project_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_project_proto_goTypes = []any{
	(*HealthRequest)(nil),        // 0: project.HealthRequest
	(*HealthResponse)(nil),       // 1: project.HealthResponse
	(*GetProjectRequest)(nil),    // 2: project.GetProjectRequest
	(*ListProjectsRequest)(nil),  // 3: project.ListProjectsRequest
	(*CreateProjectRequest)(nil), // 4: project.CreateProjectRequest
	(*ProjectResponse)(nil),      // 5: project.ProjectResponse
	(*ListProjectsResponse)(nil), // 6: project.ListProjectsResponse
	(*ProjectURLResponse)(nil),   // 7: project.ProjectURLResponse
}
var file_proto_project_proto_depIdxs = []int32{
	5, // 0: project.ListProjectsResponse.projects:type_name -> project.ProjectResponse
	0, // 1: project.ProjectService.Health:input_type -> project.HealthRequest
	2, // 2: project.ProjectService.GetProject:input_type -> project.GetProjectRequest
	3, // 3: project.ProjectService.ListProjects:input_type -> project.ListProjectsRequest
	4, // 4: project.ProjectService.CreateProject:input_type -> project.CreateProjectRequest
	2, // 5: project.ProjectService.GetProjectURL:input_type -> project.GetProjectRequest
	1, // 6: project.ProjectService.Health:output_type -> project.HealthResponse
	5, // 7: project.ProjectService.GetProject:output_type -> project.ProjectResponse
	6, // 8: project.ProjectService.ListProjects:output_type -> project.ListProjectsResponse
	5, // 9: project.ProjectService.CreateProject:output_type -> project.ProjectResponse
	7, // 10: project.ProjectService.GetProjectURL:output_type -> project.ProjectURLResponse
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_project_proto_init() }
func file_proto_project_proto_init() {
	if File_proto_project_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_project_proto_rawDesc), len(file_proto_project_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_project_proto_goTypes,
		DependencyIndexes: file_proto_project_proto_depIdxs,
		MessageInfos:      file_proto_project_proto_msgTypes,
	}.Build()
	File_proto_project_proto = out.File
	file_proto_project_proto_goTypes = nil
	file_proto_project_proto_depIdxs = nil
}
