frontend:
  image: 242201265494.dkr.ecr.eu-north-1.amazonaws.com/forge-frontend:latest
  port: 80

backend:
  image: 242201265494.dkr.ecr.eu-north-1.amazonaws.com/forge-backend:latest
  port: 8080

postgres:
  image: postgres:16
  user: forge
  password: forge123
  database: forge
  port: 5432

service:
  type: LoadBalancer