apiVersion: apps/v1
kind: Deployment

metadata:
  name: forge-backend

spec:
  replicas: 3

  selector:
    matchLabels:
      app: forge-backend

  template:
    metadata:
      labels:
        app: forge-backend

    spec:

      serviceAccountName: forge-backend-sa

      containers:
        - name: backend
          image: {{ .Values.backend.image }}
          imagePullPolicy: Always

          ports:
            - containerPort: {{ .Values.backend.port }}

          env:
            - name: POSTGRES_HOST
              value: forge-postgres

            - name: POSTGRES_PORT
              value: {{ .Values.postgres.port | quote }}

            - name: POSTGRES_USER
              value: {{ .Values.postgres.user | quote }}

            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgres.password | quote }}

            - name: POSTGRES_DB
              value: {{ .Values.postgres.database | quote }}