apiVersion: v1
kind: Service

metadata:
  name: forge-frontend

spec:
  type: ClusterIP

  selector:
    app: forge-frontend

  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}