apiVersion: v1
kind: Service

metadata:
  name: forge-postgres

spec:
  type: ClusterIP

  selector:
    app: forge-postgres

  ports:
    - port: {{ .Values.postgres.port }}
      targetPort: {{ .Values.postgres.port }}