apiVersion: apps/v1
kind: Deployment

metadata:
  name: forge-postgres

  labels:

  managed-by: forge

  app: {{ .Values.appName }}

spec:
  replicas: 1

  selector:
    matchLabels:
      app: forge-postgres

  template:
    metadata:
      labels:
        app: forge-postgres

    spec:
      containers:
        - name: postgres
          image: {{ .Values.postgres.image }}

          ports:
            - containerPort: {{ .Values.postgres.port }}

          env:
            - name: POSTGRES_USER
              value: {{ .Values.postgres.user | quote }}

            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgres.password | quote }}

            - name: POSTGRES_DB
              value: {{ .Values.postgres.database | quote }}

          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data

      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: forge-postgres-pvc